import json
import os
import sys
from datetime import datetime

# Add the project root to the path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from scripts.load_env import load_env

# Load environment variables
load_env(os.path.join(os.path.dirname(__file__), '..', '.env'))

def generate_executive_summary(processed_data):
    """
    Generates a high-level Markdown summary from the Code Team's processed JSON.
    """
    
    # Extract key data points
    timestamp = processed_data.get("source_timestamp", "N/A")
    insight = processed_data.get("actionable_insight", "No specific insight generated.")
    metrics = processed_data.get("metrics_processed", {})
    
    disk_percent = metrics.get("disk_usage_percent", "N/A")
    cpu_percent = metrics.get("cpu_usage_percent", "N/A")
    mem_percent = metrics.get("mem_usage_percent", "N/A")
    
    # Determine overall status
    overall_status = "GREEN"
    if "CRITICAL" in insight:
        overall_status = "RED"
    elif "WARNING" in insight:
        overall_status = "YELLOW"
        
    # Build the Markdown report
    report = f"""# Executive Summary Report: System Resource Analysis

**Generated By:** Features Team (FT-001)
**Generated At:** {datetime.now().isoformat()}
**Source Timestamp:** {timestamp}
**Overall Status:** **{overall_status}**

## Key Findings

The system resource analysis indicates the following status:

| Metric | Value | Status |
| :--- | :--- | :--- |
| Disk Usage | {disk_percent}% | {'🔴' if disk_percent >= 80 else '🟢'} |
| CPU Usage | {cpu_percent}% | {'🟡' if cpu_percent >= 90 else '🟢'} |
| Memory Usage | {mem_percent}% | {'🟡' if mem_percent >= 90 else '🟢'} |

## Actionable Insight

> {insight}

## Raw Data Reference

The full processed data is available in the Code Team's output topic.
"""
    return report

def start_summary_listener():
    """
    Handles the MQ subscription logic for the Features Team.
    It consumes the Code Team's output and generates the summary.
    """
    # The Features Team consumes the Code Team's output file directly for simplicity
    # In a real system, this would be a separate MQ topic.
    input_file = os.environ.get("CT_OUTPUT_FILE")
    output_file = os.environ.get("FT_OUTPUT_FILE")
    
    if not input_file or not output_file:
        print("Error: CT_OUTPUT_FILE or FT_OUTPUT_FILE environment variables not set.")
        return

    # 1. Read the Code Team's processed data
    try:
        with open(input_file, 'r') as f:
            processed_data = json.load(f)
    except FileNotFoundError:
        print(f"Features Team (FT-001) Subscriber: Code Team output file not found at {input_file}.")
        return
    except Exception as e:
        print(f"Error reading Code Team output: {e}")
        return

    # 2. Generate the summary
    summary_report = generate_executive_summary(processed_data)

    # 3. Write the final Markdown report
    with open(output_file, 'w') as f:
        f.write(summary_report)
        
    print(f"Features Team (FT-001) successfully generated Executive Summary to {output_file}")

if __name__ == "__main__":
    start_summary_listener()
